### ISSUE TITLE
WinError 126

### ISSUE THREAD

**Issue by sherloked** [schwifty42069/piptv#10]
I've installed the requirements, but on running the script, I get this error. Photo attached. 
![Error!](https://user-images.githubusercontent.com/43991317/65323112-260e7500-dbc6-11e9-863d-55fb69789fe0.png)

**Comment by ZoleeHUN** [comment]
Your error indicates that you don't have VLC installed, install it.
(If you do have it installed make sure it is installed under "C:\Program Files\VideoLAN\VLC")

**Comment by sherloked** [comment]
I'd already installed VLC before this. Does this need the 32 bit version
only? I've only installed the 64 bit, so that could be the issue.

**Comment by ZoleeHUN** [comment]
I also have 64 bit VLC, are you sure yours is installed under C:\Program Files\VideoLAN\VLC?
If not you could edit the code under `instance_args += "--plugins-path=C:\Program Files\VideoLAN\VLC\plugins"` to point to the correct path

**Comment by sherloked** [comment]
Yes, I'm sure it's installed right there. It's the default location and I
didn't change anything.

**Comment by schwifty42069** [comment]
Yeah, you're getting this because the script can't find the vlc binary.

**Comment by sherloked** [comment]
I reinstalled VLC, default location, same error again. Sucks. :/

**Comment by schwifty42069** [comment]
What version of windows are you running?

**Comment by sherloked** [comment]
I'm on Windows 10, 64 bit, latest updates installed.

**Comment by schwifty42069** [comment]
can you open a cmd prompt and show me the output of 

echo %PATH%

**Comment by sherloked** [comment]
Here you go:
![Annotation 2019-09-20 213725](https://user-images.githubusercontent.com/43991317/65341853-f6279780-dbee-11e9-99a4-3d55051dc751.png)

**Comment by schwifty42069** [comment]
Alright, it doesn't look like you have python in your path, but I don't think that's the issue. Can you show me the output of

dir C:\Program Files\VideoLAN\VLC\plugins

Also, when did you download the version of piptv you're using? Just curious if it was today

**Comment by schwifty42069** [comment]
Also what version of python do you have installed? Latest? (3.7.x)

**Comment by sherloked** [comment]
I'd downloaded the version which was on here yesterday. My Python version is the latest one, 3.7.4
Funnily enough, that command says the path does not exist, but it really does. I've attached a screenshot of the folder too. 
![Annotation 2019-09-20 214852](https://user-images.githubusercontent.com/43991317/65342586-ae097480-dbf0-11e9-8b12-68d2e8cc758e.png)
![Annotation 2019-09-20 214933](https://user-images.githubusercontent.com/43991317/65342589-aea20b00-dbf0-11e9-8903-4a0509c8e7fd.png)

**Comment by schwifty42069** [comment]
that's likely our problem then! Yay. Can you right click on the plugins folder for me and click copy as text, and paste here what it thinks the path is?

**Comment by schwifty42069** [comment]
Also, do you know how to add to your path environment variable? Because we're gonna add your python dist-packages folder to path too. Then I will have you try again

**Comment by schwifty42069** [comment]
actually before we do that though. can you open a python shell and type

import requests

from bs4 import BeautifulSoup

import vlc

and show me what it outputs?

**Comment by sherloked** [comment]
"Copy as text" doesn't seem to be showing up as an option to me on the right click. However, I noticed all the folders and files are set to "Read Only" for some reason. Could that be the issue? 

No, I don't. Please help me to do that! 
The same Win Error 126 pops up on those commands too. 
![Annotation 2019-09-20 215759](https://user-images.githubusercontent.com/43991317/65343113-dc3b8400-dbf1-11e9-86b7-82fce04715e4.png)

**Comment by schwifty42069** [comment]
Hmmm I don't think so. I can help you do that, though I don't think it should be necessary. Exit the python shell, and in the cmd prompt type

pip install python-vlc

and show me the output of that. Just curious.

**Comment by sherloked** [comment]
![Annotation 2019-09-20 220338](https://user-images.githubusercontent.com/43991317/65343409-89ae9780-dbf2-11e9-98bc-0b77b7fcfead.png)

**Comment by schwifty42069** [comment]
Okay, so go the explorer where you had the Program Files\VLC\plugins open, if you right click the folder that says plugins at the top, does it give you the option to copy the address?

**Comment by sherloked** [comment]
Nope, no such option. Here's a screenshot of the Properties though.
![Annotation 2019-09-20 220731](https://user-images.githubusercontent.com/43991317/65343702-3c7ef580-dbf3-11e9-9131-833ab3a9eda4.png)

**Comment by sherloked** [comment]
"C:\Program Files\VideoLAN\VLC\plugins"

**Comment by schwifty42069** [comment]
Okay let's add the VLC plugins to your path and restart your pc and try again.

In windows search type libvlc.dll, take note of the path where it's located
In Search, search for and then select: System (Control Panel)
Click the Advanced system settings link.
Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit.
In the Edit System Variable window, put a semicolon at the end of your existing path, and add the full path of libvlc.dll to the end. Click Ok.

restart your pc and try again

**Comment by schwifty42069** [comment]
If you get lost, a great explanation for fixing exactly the problem you're having can be found here. Let me know if this resolves your issue!

https://stackoverflow.com/a/47183893

**Comment by sherloked** [comment]
Hey, I tried a couple of the methods mentioned in the stackoverflow thread, but they both didn't seem to work. I tried the `setx` method too, but that returned an error saying "Access is denied to the directory". I fear that may be the issue; access being denied to the file. Any workarounds? Editing the permissions for Program Files seems to be disabled for all users. Everything is grayed-out.

**Comment by schwifty42069** [comment]
I just added an additional doc to the repo of the method used by @ZoleeHUN which has helped a bunch of people get this going on windows 10, can you try this guide for me? I think you may have forgot to do a single step as root (or admin for windows)

https://github.com/schwifty42069/piptv/blob/master/doc/windows.md

If this doesn't get you going, we'll keep troubleshooting. I am getting a windows 10 VM setup so I can be hopefully be a bit more helpful.

**Comment by sherloked** [comment]
Thanks a lot for going the extra mile to help! I shall redo every single step and revert to you. Fingers crossed!

**Comment by schwifty42069** [comment]
Haha no problem, thank you for your patience. I hate when stuff like this happens -_-

**Comment by sherloked** [comment]
Heyyy the particular problem got fixed, the script at least runs! :)

However there's a new error now, when trying to tune into a channel. Do I open a new issue or continue it here?

**Comment by schwifty42069** [comment]
We can continue it here. This is good news at least. What is the new error?

**Comment by sherloked** [comment]
Another traceback error, but of a different type. Here's the screenshot: 
![Annotation 2019-09-21 003602](https://user-images.githubusercontent.com/43991317/65352275-e0729c00-dc07-11e9-8b17-c5d0d94f7d2c.png)

**Comment by schwifty42069** [comment]
I saw someone else with this earlier, let me do some debugging and see if I can figure out what's up.

**Comment by sherloked** [comment]
Alright cool, thanks again!

**Comment by schwifty42069** [comment]
Did you reclone the repository when you just redid the steps?

**Comment by schwifty42069** [comment]
Do me a favor, open a python3 shell and type the following in it:

import requests
from bs4 import BeautifulSoup as Soup

bsoup = Soup(requests.get('http://ustvgo.tv/nfl-network-live-free/').text, 'html.parser')

print(bsoup)

I'm just curious to see if you're getting data back from the request.

**Comment by schwifty42069** [comment]
I think it's an issue creating the VLC instance, I am going to put another version of the script up that will log every single thing happens so we can see.

**Comment by schwifty42069** [comment]
I just pushed a commit that allows a debug flag to be passed when you type the channel name. So instead of typing, say, espn by itself, type espn --debug and send a post the giant chunk of output you get

**Comment by sherloked** [comment]
`[1;37;49m>> espn --debug

[1;33;49mTrying to tune to espn --debug...

[000001f641c0f430] main libvlc debug: VLC media player - 3.0.8 Vetinari
[000001f641c0f430] main libvlc debug: Copyright ┬⌐ 1996-2019 the VideoLAN team
[000001f641c0f430] main libvlc debug: revision 3.0.8-0-gf350b6b5a7
[000001f641c0f430] main libvlc debug: configured with ../extras/package/win32/../../../configure  '--enable-update-check' '--enable-lua' '--enable-faad' '--enable-flac' '--enable-theora' '--enable-avcodec' '--enable-merge-ffmpeg' '--enable-dca' '--enable-mpc' '--enable-libass' '--enable-schroedinger' '--enable-realrtsp' '--enable-live555' '--enable-dvdread' '--enable-shout' '--enable-goom' '--enable-caca' '--enable-qt' '--enable-skins2' '--enable-sse' '--enable-mmx' '--enable-libcddb' '--enable-zvbi' '--disable-telx' '--enable-nls' '--host=x86_64-w64-mingw32' '--with-breakpad=https://win.crashes.videolan.org' 'host_alias=x86_64-w64-mingw32' 'PKG_CONFIG_LIBDIR=/home/jenkins/workspace/vlc-release/windows/vlc-release-win32-x64/contrib/x86_64-w64-mingw32/lib/pkgconfig'
[000001f641c0f430] main libvlc debug: plug-ins loaded: 494 modules
[000001f641c042c0] main logger debug: looking for logger module matching "any": 2 candidates
[000001f641c042c0] main logger debug: using logger module "console"
[000001f641c0f430] main libvlc debug: translation test: code is "C"
[000001f641c6a0e0] main keystore debug: looking for keystore module matching "memory": 3 candidates
[000001f641c6a0e0] main keystore debug: using keystore module "memory"
[000001f641c0f430] main libvlc debug: CPU has capabilities MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 FPU
[000001f641c14080] main playlist debug: creating audio output
[000001f641c166e0] main audio output debug: looking for audio output module matching "any": 6 candidates
[000001f641c166e0] mmdevice audio output debug: using default device
[000001f641c166e0] mmdevice audio output debug: version 2 session control unavailable
[000001f641c166e0] mmdevice audio output debug: volume from -65.250000 dB to +0.000000 dB with 0.031250 dB increments
[000001f641c166e0] main audio output debug: using audio output module "mmdevice"
[000001f641c14080] main playlist debug: keeping audio output
[000001f641be5360] main generic debug: creating audio output
[000001f641c07340] main input debug: Creating an input for preparsing 'plugins'
[000001f641c163c0] main audio output debug: looking for audio output module matching "any": 6 candidates
[000001f641c0aca0] main input debug: Creating an input for preparsing 'vlc'
[000001f641c25e40] main meta fetcher debug: looking for meta fetcher module matching "any": 1 candidates
[000001f641c163c0] mmdevice audio output debug: using default device
[000001f641c25e40] lua meta fetcher debug: Trying Lua scripts in C:\Users\vyash\AppData\Roaming\vlc\lua\meta\fetcher
[000001f641c163c0] mmdevice audio output debug: version 2 session control unavailable
[000001f641c25e40] lua meta fetcher debug: Trying Lua scripts in C:\Program Files\VideoLAN\VLC\lua\meta\fetcher
[000001f641c163c0] mmdevice audio output debug: volume from -65.250000 dB to +0.000000 dB with 0.031250 dB increments
[000001f641c25e40] main meta fetcher debug: no meta fetcher modules matched
[000001f641c163c0] main audio output debug: using audio output module "mmdevice"
[000001f641c25820] main art finder debug: looking for art finder module matching "any": 2 candidates
[000001f641be5360] main generic debug: keeping audio output
[000001f641c25820] lua art finder debug: Trying Lua scripts in C:\Users\vyash\AppData\Roaming\vlc\lua\meta\art
[000001f641c25820] lua art finder debug: Trying Lua scripts in C:\Program Files\VideoLAN\VLC\lua\meta\art
[000001f641c25820] lua art finder debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\meta\art\00_musicbrainz.luac
[000001f641c25820] lua art finder debug: skipping script (unmatched scope) C:\Program Files\VideoLAN\VLC\lua\meta\art\00_musicbrainz.luac
[000001f641c25820] lua art finder debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\meta\art\01_googleimage.luac
[000001f641c25820] lua art finder debug: skipping script (unmatched scope) C:\Program Files\VideoLAN\VLC\lua\meta\art\01_googleimage.luac
[000001f641c25820] lua art finder debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\meta\art\02_frenchtv.luac
[000001f641c25820] lua art finder debug: skipping script (unmatched scope) C:\Program Files\VideoLAN\VLC\lua\meta\art\02_frenchtv.luac
[000001f641c25820] lua art finder debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\meta\art\03_lastfm.luac
[000001f641c25820] lua art finder debug: skipping script (unmatched scope) C:\Program Files\VideoLAN\VLC\lua\meta\art\03_lastfm.luac
[000001f641c25820] main art finder debug: no art finder modules matched
[000001f641c25580] main meta fetcher debug: looking for meta fetcher module matching "any": 1 candidates
[000001f641c25580] lua meta fetcher debug: Trying Lua scripts in C:\Users\vyash\AppData\Roaming\vlc\lua\meta\fetcher
[000001f641c25580] lua meta fetcher debug: Trying Lua scripts in C:\Program Files\VideoLAN\VLC\lua\meta\fetcher
[000001f641c25580] main meta fetcher debug: no meta fetcher modules matched
[000001f641c25660] main art finder debug: looking for art finder module matching "any": 2 candidates
[000001f641c25660] lua art finder debug: Trying Lua scripts in C:\Users\vyash\AppData\Roaming\vlc\lua\meta\art
[000001f641c25660] lua art finder debug: Trying Lua scripts in C:\Program Files\VideoLAN\VLC\lua\meta\art
[000001f641c25660] lua art finder debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\meta\art\00_musicbrainz.luac
[000001f641c25660] lua art finder debug: skipping script (unmatched scope) C:\Program Files\VideoLAN\VLC\lua\meta\art\00_musicbrainz.luac
[000001f641c25660] lua art finder debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\meta\art\01_googleimage.luac
[000001f641c25660] lua art finder debug: skipping script (unmatched scope) C:\Program Files\VideoLAN\VLC\lua\meta\art\01_googleimage.luac
[000001f641c25660] lua art finder debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\meta\art\02_frenchtv.luac
[000001f641c25660] lua art finder debug: skipping script (unmatched scope) C:\Program Files\VideoLAN\VLC\lua\meta\art\02_frenchtv.luac
[000001f641c25660] lua art finder debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\meta\art\03_lastfm.luac
[000001f641c25660] lua art finder debug: skipping script (unmatched scope) C:\Program Files\VideoLAN\VLC\lua\meta\art\03_lastfm.luac
[000001f641c25660] main art finder debug: no art finder modules matched
Traceback (most recent call last):
  File "piptv.py", line 180, in <module>
    main()
  File "piptv.py", line 173, in main
    stb.tune_to_channel(command.split(" --debug")[0])
  File "piptv.py", line 126, in tune_to_channel
    self.player.set_mrl(hotlink)
  File "C:\Python37\lib\site-packages\vlc.py", line 3331, in set_mrl
    m = self.get_instance().media_new(mrl, *options)
  File "C:\Python37\lib\site-packages\vlc.py", line 1908, in media_new
    if ':' in mrl and mrl.index(':') > 1:
TypeError: argument of type 'NoneType' is not iterable`

**Comment by schwifty42069** [comment]
Well shit, that was not as illuminating as I had hoped -_- haha. Can you try those python commands above for me in a python shell?

**Comment by sherloked** [comment]
<!DOCTYPE html>




 <html class="no-js" lang="en-US"> 
<head>
<title>Access denied | ustvgo.tv used Cloudflare to restrict access</title>
<meta charset="utf-8"/>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="noindex, nofollow" name="robots"/>
<meta content="width=device-width,initial-scale=1,maximum-scale=1" name="viewport"/>
<link href="/cdn-cgi/styles/cf.errors.css" id="cf_styles-css" media="screen,projection" rel="stylesheet" type="text/css"/>

<style type="text/css">body{margin:0;padding:0}</style>
<script src="/cdn-cgi/scripts/zepto.min.js" type="text/javascript"></script>
<script src="/cdn-cgi/scripts/cf.common.js" type="text/javascript"></script>
</head>
<body>
<div id="cf-wrapper">
<div class="cf-alert cf-alert-error cf-cookie-error" data-translate="enable_cookies" id="cookie-alert">Please enable cookies.</div>
<div class="cf-error-details-wrapper" id="cf-error-details">
<div class="cf-wrapper cf-header cf-error-overview">
<h1>
<span class="cf-error-type" data-translate="error">Error</span>
<span class="cf-error-code">1005</span>
<small class="heading-ray-id">Ray ID: 51967807ecd0d5ab • 2019-09-20 20:14:59 UTC</small>
</h1>
<h2 class="cf-subheadline">Access denied</h2>
</div>
<section></section>
<div class="cf-section cf-wrapper">
<div class="cf-columns two">
<div class="cf-column">
<h2 data-translate="what_happened">What happened?</h2>
<p>The owner of this website (ustvgo.tv) has banned the autonomous system number (ASN) your IP address is in (9829) from accessing this website.</p>
</div>
</div>
</div>
<div class="cf-error-footer cf-wrapper">
<p>
<span class="cf-footer-item">Cloudflare Ray ID: <strong>51967807ecd0d5ab</strong></span>
<span class="cf-footer-separator">•</span>
<span class="cf-footer-item"><span>Your IP</span>: 117.220.112.162</span>
<span class="cf-footer-separator">•</span>
<span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
</p>
</div>
</div>
</div>
<script type="text/javascript">
  window._cf_translation = {};


</script>
</body>
</html>


Well, looks like my IP's been banned from the server for some reason. xD

**Comment by schwifty42069** [comment]
Well shit! There's our problem! D:

**Comment by sherloked** [comment]
So does that mean the script is unusable to me, seeing as my IP is blocked? :(

**Comment by schwifty42069** [comment]
For now anyways, yes ): I will try to think of a work-around. Can you try in a python shell these commands for me?

import vlc

player = vlc.MediaPlayer("http://live.savitar.tv/VH1/myStream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9OS8yMC8yMDE5IDg6MjM6MjcgUE0maGFzaF92YWx1ZT1maGdBeG16QS9CK3k2YXZLSVBqclhBPT0mdmFsaWRtaW51dGVzPTM2MCZpZD0w")

player.play()

**Comment by sherloked** [comment]
This one worked! The stream is working great now.

**Comment by schwifty42069** [comment]
Yeah, so those are the CDN hotlinks that the script scrapes. You can try to route through a proxy. To get the script to use it, you will have to first find one that works, and then setup an environment variable called http_proxy with the IP of the proxy you chose

**Comment by schwifty42069** [comment]
Unfortunately, the hotlinks like the one I gave you only last for 6 hours, which is why the script fetches them anytime you tune to a channel. So barring setting up a proxy or VPN, you're probably SOL. D:

**Comment by sherloked** [comment]
Dang, I'm on the school network right now. VPNs are kinda off the table I'd say. Sucks. :(

Thanks a lot for trying though. Much appreciated. Cheers!

**Comment by schwifty42069** [comment]
You may still be able to get a proxy to work! But if not, I'm sorry ]: Thanks for hanging in there!
