### ISSUE TITLE
Script not working on Ubuntu

### ISSUE THREAD

**Issue by blackoutworm** [schwifty42069/piptv#21]
Error code:

> Trying to tune to abc...

Traceback (most recent call last):
  File "piptv.py", line 181, in <module>
    main()
  File "piptv.py", line 177, in main
    stb.tune_to_channel(command)
  File "piptv.py", line 127, in tune_to_channel
    self.player.set_mrl(hotlink)
  File "/home/chris/.local/lib/python3.7/site-packages/vlc.py", line 3331, in set_mrl
    m = self.get_instance().media_new(mrl, *options)
  File "/home/chris/.local/lib/python3.7/site-packages/vlc.py", line 1908, in media_new
    if ':' in mrl and mrl.index(':') > 1:
TypeError: argument of type 'NoneType' is not iterable

**Comment by schwifty42069** [comment]
This script has been replaced by [pmg](https://github.com/schwifty42069/pmg)

You can install it with pip using the following command:

```
python3 -m pip install piptv_pmg
```

The new script generates an m3u with all 80 channels which can be used in MPV (or almost any media player)
