### ISSUE TITLE
error in tuning to a channel

### ISSUE THREAD

**Issue by gitricko** [schwifty42069/piptv#22]
```ssh
Trying to tune to vh1...

Traceback (most recent call last):
  File "piptv.py", line 181, in <module>
    main()
  File "piptv.py", line 177, in main
    stb.tune_to_channel(command)
  File "piptv.py", line 127, in tune_to_channel
    self.player.set_mrl(hotlink)
  File "/Users/n361268/miniconda3/envs/piptv/lib/python3.8/site-packages/vlc.py", line 3331, in set_mrl
    m = self.get_instance().media_new(mrl, *options)
  File "/Users/n361268/miniconda3/envs/piptv/lib/python3.8/site-packages/vlc.py", line 1908, in media_new
    if ':' in mrl and mrl.index(':') > 1:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by cometstyles** [comment]
pretty sure this script is now dead as that site has updated its settings
