### ISSUE TITLE
"IndexError: list index out of range" mac

### ISSUE THREAD

**Issue by vigneshvelu** [schwifty42069/piptv#3]
Hi there:)

Thank you for creating the app. I tried using it. I installed all the requirements. Yet, I am getting this error. Is there something I am doing wrong or is it a bug? Thank you:)

```
>> espn

Trying to tune to espn...

Traceback (most recent call last):
  File "/Users/vnvy/Documents/socialamnesia/piptv/piptv.py", line 152, in <module>
    main()
  File "/Users/vnvy/Documents/socialamnesia/piptv/piptv.py", line 148, in main
    stb.tune_to_channel(command)
  File "/Users/vnvy/Documents/socialamnesia/piptv/piptv.py", line 109, in tune_to_channel
    hotlink = self.get_hls_hotlink(channel)
  File "/Users/vnvy/Documents/socialamnesia/piptv/piptv.py", line 103, in get_hls_hotlink
    return bsoup.findAll("script")[15].next_element.split(" file: ")[1].split(',')[0].strip("\'")
IndexError: list index out of range
```

**Comment by schwifty42069** [comment]
I don't have a way to test for OSX right now, unfortunately, but it looks like a common issue. Give me a bit to start the windows testing and I will get back to you! This doesn't look like a dependency issue, so I think you did everything correctly. Probably just a little bug.

**Comment by Aesir9** [comment]
Had the same problem, here a is a solution which works for windows:
```
    def get_hls_hotlink(self, channel):
        try:
            data = requests.get(self.channel_dict[channel.lower()]).text
            import re
            re_link = r"file: '(?P<url>http://.*)'"
            match = re.search(re_link, data)
            if match:
                match = match.groupdict()
                return match['url']
        except KeyError:
            print("Invalid channel name!\n")
            return 1
```

**Comment by vigneshvelu** [comment]
@Aesir9 I replaced that function code with yours. I am getting the following error:
```
>> espn

Trying to tune to espn...

Traceback (most recent call last):
  File "/Users/vnvy/Documents/socialamnesia/piptv/piptv.py", line 156, in <module>
    main()
  File "/Users/vnvy/Documents/socialamnesia/piptv/piptv.py", line 152, in main
    stb.tune_to_channel(command)
  File "/Users/vnvy/Documents/socialamnesia/piptv/piptv.py", line 116, in tune_to_channel
    self.player.set_mrl(hotlink)
  File "/Users/vnvy/Documents/socialamnesia/piptv/lib/python3.7/site-packages/vlc.py", line 3331, in set_mrl
    m = self.get_instance().media_new(mrl, *options)
  File "/Users/vnvy/Documents/socialamnesia/piptv/lib/python3.7/site-packages/vlc.py", line 1908, in media_new
    if ':' in mrl and mrl.index(':') > 1:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by amadeus-alt** [comment]
@Aesir9 also works on Debian.

**Comment by baddles** [comment]
> @Aesir9 I replaced that function code with yours. I am getting the following error:
> 
> ```
> >> espn
> 
> Trying to tune to espn...
> 
> Traceback (most recent call last):
>   File "/Users/vnvy/Documents/socialamnesia/piptv/piptv.py", line 156, in <module>
>     main()
>   File "/Users/vnvy/Documents/socialamnesia/piptv/piptv.py", line 152, in main
>     stb.tune_to_channel(command)
>   File "/Users/vnvy/Documents/socialamnesia/piptv/piptv.py", line 116, in tune_to_channel
>     self.player.set_mrl(hotlink)
>   File "/Users/vnvy/Documents/socialamnesia/piptv/lib/python3.7/site-packages/vlc.py", line 3331, in set_mrl
>     m = self.get_instance().media_new(mrl, *options)
>   File "/Users/vnvy/Documents/socialamnesia/piptv/lib/python3.7/site-packages/vlc.py", line 1908, in media_new
>     if ':' in mrl and mrl.index(':') > 1:
> TypeError: argument of type 'NoneType' is not iterable
> ```

Can you try aligning the codes so it looks exactly like above? Python use strict indentation format, and I think you must have pasted the code unevenly.

**Comment by VibSel** [comment]
Facing the same issue.
`Trying to tune to abc...

Traceback (most recent call last):
  File "piptv.py", line 165, in <module>
    main()
  File "piptv.py", line 161, in main
    stb.tune_to_channel(command)
  File "piptv.py", line 113, in tune_to_channel
    hotlink = self.get_hls_hotlink(channel)
  File "piptv.py", line 107, in get_hls_hotlink
    return bsoup.findAll("script")[15].next_element.split(" file: ")[1].split(',')[0].strip("\'")
IndexError: list index out of range
`

**Comment by schwifty42069** [comment]
Just pushed a quick and dirty patch, try it now. I will be doing a full refactor to remove the need to have the list of script elements all together, but this should work for now. Closing this, reopen it if you still have issues with the new stacktrace

**Comment by vigneshvelu** [comment]
Still doesn't work. I tried the new code. 

```
Trying to tune to espn...

Traceback (most recent call last):
  File "piptv.py", line 167, in <module>
    main()
  File "piptv.py", line 163, in main
    stb.tune_to_channel(command)
  File "piptv.py", line 118, in tune_to_channel
    self.player.set_mrl(hotlink)
  File "/usr/local/lib/python3.7/site-packages/vlc.py", line 3331, in set_mrl
    m = self.get_instance().media_new(mrl, *options)
  File "/usr/local/lib/python3.7/site-packages/vlc.py", line 1908, in media_new
    if ':' in mrl and mrl.index(':') > 1:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by Pau1fitz** [comment]
getting the same as @vigneshvelu on mac
