### ISSUE TITLE
Problem in windows 10

### ISSUE THREAD

**Issue by einherjarr** [schwifty42069/piptv#6]
python version: 3.7.3
Requirements.txt installed and up-to-date.

You warned windows users but just wanted to let you know about error

Error when you run script:

`PS C:\Users\------\Desktop\piptv-master> python .\piptv.py
Traceback (most recent call last):
  File ".\piptv.py", line 3, in <module>
    import vlc

  File "C:\Users\------\AppData\Local\Programs\Python\Python37\lib\site-packages\vlc.py", line 207, in <module>
    dll, plugin_path  = find_lib()
  File "C:\Users\------\AppData\Local\Programs\Python\Python37\lib\site-packages\vlc.py", line 167, in find_lib
    dll = ctypes.CDLL(libname)
  File "C:\Users\------\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found`

**Comment by ZoleeHUN** [comment]
Make sure that VLC is installed I had the same error, just had to install VLC for Windows

**Comment by schwifty42069** [comment]
I second @ZoleeHUN, looks like you're missing VLC. Closing for now, if you still have problems check back here later I will have step by step docs up.
